site_name: Wetboek DamskoRP
site_url: http://regels.damsko-rp.nl
site_author: 'DamskoRP'

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Risicogebieden: risico-gebieden.md
  - Douanegebieden: douanegebieden.md
  - NOTAM: notam.md
  - Belastingen: belastingen.md
  - Streamen op DamskoRP: streamen.md
  - Offroad Voertuigen: offroadvoertuigen.md
  - Kosten:
    - Ambulance: kosten/ambulance.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md
    - Vliegschool: kosten/vliegschool.md

theme:
  name: material
  language: nl
  logo: img/damsko-logo2.png
  favicon: img/favicon.png
  palette:
      # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep blue
      accent: deep blue
      toggle:
        icon: material/weather-sunny
        name: Donkere Modus

      # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep blue
      accent: deep blue
      toggle:
        icon: material/weather-night
        name: Lichte Modus

copyright: © DamskoRP 2022

plugins:
  - search:
      lang: nl
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false

markdown_extensions:
  - attr_list
  - tables

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://dsc.gg/damsko-rp
    - icon: fontawesome/solid/globe
      link: https://www.damsko-rp.nl
